/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;


import Controller.Control;
import Model.ConexionDB;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.URLDecoder;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import org.jdesktop.swingx.JXTaskPane;

/**
 *
 * @author 9
 */
public class ConsolaAdmin extends javax.swing.JFrame {

    public ConsolaAdmin() {
        initComponents();
        GrupoBotRepLab.add(Eq_status);
        GrupoBotRepLab.add(Eq_number);
    }
    Control Control = new Control();
    String path="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jFrame1 = new javax.swing.JFrame();
        //jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        //TaskPaneReports = new org.jdesktop.swingx.JXTaskPane();
        //TaskPaneReports.add(new AbstractAction(){
          //  {
          //      putValue(Action.NAME,"Generar reportes");
          //  }
          //  public void actionPerformed(ActionEvent e){
            //    ToggleRP();
            //}
        //});
        GrupoBotRepLab = new javax.swing.ButtonGroup();
        GrupoReportes = new javax.swing.ButtonGroup();
        jXTaskPaneContainer1 = new org.jdesktop.swingx.JXTaskPaneContainer();
        jXTaskPaneContainer1.add(TaskPaneReports);
        TaskPaneLabs = TaskPaneLabs = new JXTaskPane();
        TaskPaneLabs.add(new AbstractAction(){
            {
                putValue(Action.NAME,"Registrar Laboratorio");
            }
            public void actionPerformed(ActionEvent e){
                ToggleAL();
            }
        });
        TaskPaneLabs.add(new AbstractAction(){
            {
                putValue(Action.NAME,"Generar Reportes  \nde Laboratorios");
            }
            public void actionPerformed(ActionEvent e){
                ToggleRL();
            }
        });
        TaskPaneStock = new org.jdesktop.swingx.JXTaskPane();
        TaskPaneStock.add(new AbstractAction(){
            {
                putValue(Action.NAME,"Registrar equipos \n nuevos");
            }
            public void actionPerformed(ActionEvent e){
                ToggleERP();

            }
        });
        TaskPaneStock.add(new AbstractAction(){
            {
                putValue(Action.NAME,"Eliminar equipos");
            }
            public void actionPerformed(ActionEvent e){
                ToggleEDP();
            }
        });
        TaskPaneUsrs = new org.jdesktop.swingx.JXTaskPane();
        TaskPaneUsrs.add(new AbstractAction(){
            {
                putValue(Action.NAME,"Actualizar datos \n de usuarios");
            }
            public void actionPerformed(ActionEvent e){
                ToggleUUP();
            }
        });
        TaskPaneMantainance = new org.jdesktop.swingx.JXTaskPane();
        TaskPaneMantainance.add(new AbstractAction(){
            {
                putValue(Action.NAME,"Limpieza de \n registros");
            }
            public void actionPerformed(ActionEvent e){
                ToggleTCP();
            }
        });
        closeAdmin = new javax.swing.JButton();
        closeAdmin.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                new GUI_Usr().lanza();
                dispose();
            }
        });
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Panel_RL = new javax.swing.JPanel();
        Panel_RL.setVisible(false);
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameLab = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Locacion = new javax.swing.JTextField();
        Locacion.addKeyListener(new KeyAdapter(){
            public void keyPressed(KeyEvent e){
                if(NameLab.getText()!=null&&Locacion.getText()!=null){
                    BotonRegLab.setEnabled(true);
                }
            }
        });
        BotonRegLab = new javax.swing.JButton();
        BotonRegLab.setEnabled(false);
        BotonRegLab.addActionListener(new ActionListener(){

            @Override
            public void actionPerformed(ActionEvent e) {
                Control.RegistrarCentro(NameLab.getText(),Locacion.getText());
            }

        });
        jLabel38 = new javax.swing.JLabel();
        Panel_RepL = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Eq_number = new javax.swing.JRadioButton();
        Eq_status = new javax.swing.JRadioButton();
        RepLabBox = new javax.swing.JComboBox();
        RepLabButton = new javax.swing.JButton();
        RepLabButton.setEnabled(false);
        jLabel6 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        Eq_RegPane = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Eq_Name = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        EqStatus_box = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        EqPlace_Box = new javax.swing.JComboBox();
        RegEqButton = new javax.swing.JButton();
        RegEqButton.setEnabled(false);
        jLabel40 = new javax.swing.JLabel();
        Eq_DropPane = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        EqName_Drop_Box = new javax.swing.JComboBox();
        EqDrop_Button = new javax.swing.JButton();
        EqDrop_Button.setEnabled(false);
        jLabel36 = new javax.swing.JLabel();
        SelectLab_DropEq = new javax.swing.JComboBox();
        SelectLab_DropEq.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                EqName_Drop_Box.setModel(new DefaultComboBoxModel(Control.ComboFill2("Nombre_Eq","Ubicacion_Eq",SelectLab_DropEq.getSelectedItem().toString(),"Equipo")));
            }
        });
        jLabel41 = new javax.swing.JLabel();
        Usr_UpdatePane = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Upd_Matricula = new javax.swing.JTextField();
        Upd_Name = new javax.swing.JTextField();
        UPD_AP_P = new javax.swing.JTextField();
        Upd_AP_M = new javax.swing.JTextField();
        Upd_Pass = new javax.swing.JPasswordField();
        Upd_Button = new javax.swing.JButton();
        Upd_Button.setEnabled(false);
        Upd_RevPswd = new javax.swing.JPasswordField();
        Upd_RevPswd.addKeyListener(new KeyAdapter(){
            public void keyPressed(KeyEvent e){
                if(Upd_Matricula.getText()!=null&&Upd_Name.getText()!=null&&UPD_AP_P.getText()!=null&&Upd_AP_M.getText()!=null&&Upd_Pass.getText()!=null&&Upd_RevPswd.getText()!=null){
                    Upd_Button.setEnabled(true);
                }
            }
        });

        //&&UPD_AP_P.getText()!=null&&Upd_AP_M.getText()!=null&&Upd_Pass.getText()!=null&&Upd_RevPswd.getText()!=null
        jLabel42 = new javax.swing.JLabel();
        ReportsPane = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        RBType1 = new javax.swing.JRadioButton();
        RBType2 = new javax.swing.JRadioButton();
        RBType3 = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        Repo_Lab = new javax.swing.JComboBox();
        Repo_Lab.addActionListener (new ActionListener () {
            public void actionPerformed(ActionEvent e) {
                Repo_Eq.setModel(new DefaultComboBoxModel(Control.ComboFill2("Nombre_Eq","Ubicacion_Eq",Repo_Lab.getSelectedItem().toString(),"Equipo")));
            }
        });
        jLabel23 = new javax.swing.JLabel();
        Repo_Eq = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        DiaIni = new javax.swing.JComboBox();
        jLabel25 = new javax.swing.JLabel();
        MesIni = new javax.swing.JComboBox();
        jLabel26 = new javax.swing.JLabel();
        AnoIni = new javax.swing.JComboBox();
        jLabel27 = new javax.swing.JLabel();
        HoraIni = new javax.swing.JComboBox();
        jLabel28 = new javax.swing.JLabel();
        MinIni = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        DiaFin = new javax.swing.JComboBox();
        MesFin = new javax.swing.JComboBox();
        AnoFin = new javax.swing.JComboBox();
        HoraFin = new javax.swing.JComboBox();
        MinFin = new javax.swing.JComboBox();
        RepoButton = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        TempCleanPane = new javax.swing.JPanel();
        cleanButton = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        //TaskPaneReports.setBackground(new java.awt.Color(210, 210, 255));
        //TaskPaneReports.setToolTipText("Reportes");
        //TaskPaneReports.setName("TaskPaneReports"); // NOI18N

        setTitle("Consola de administrador de CAL");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("ventana"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 750));
        setResizable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, org.jdesktop.beansbinding.ELProperty.create("${defaultCloseOperation}"), this, org.jdesktop.beansbinding.BeanProperty.create("defaultCloseOperation"));
        bindingGroup.addBinding(binding);

        jXTaskPaneContainer1.setBackground(new java.awt.Color(14, 67, 117));
        jXTaskPaneContainer1.setMinimumSize(new java.awt.Dimension(190, 336));
        jXTaskPaneContainer1.setName(""); // NOI18N
        jXTaskPaneContainer1.setPreferredSize(new java.awt.Dimension(190, 750));
        org.jdesktop.swingx.VerticalLayout verticalLayout1 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout1.setGap(14);
        jXTaskPaneContainer1.setLayout(verticalLayout1);

        //TaskPaneLabs.setBackground(new java.awt.Color(210, 210, 255));
        //TaskPaneLabs.setToolTipText("Gestionar laboratorios");
        //TaskPaneLabs.setName("TaskPaneLabs"); // NOI18N
        //jXTaskPaneContainer1.add(TaskPaneLabs);

        //TaskPaneStock.setBackground(new java.awt.Color(210, 210, 255));
        //TaskPaneStock.setToolTipText("Gestionar equipos");
        //TaskPaneStock.setName("TaskPaneStock"); // NOI18N
        //jXTaskPaneContainer1.add(TaskPaneStock);

        //TaskPaneUsrs.setBackground(new java.awt.Color(210, 210, 255));
        //TaskPaneUsrs.setToolTipText("Gestionar usuarios");
        //TaskPaneUsrs.setName("TaskPaneUsrs"); // NOI18N
        //jXTaskPaneContainer1.add(TaskPaneUsrs);

        //TaskPaneMantainance.setBackground(new java.awt.Color(210, 210, 255));
        //TaskPaneMantainance.setToolTipText("Mantenimiento");
        //TaskPaneMantainance.setName("TaskPaneMantainance"); // NOI18N
        ///jXTaskPaneContainer1.add(TaskPaneMantainance);

        closeAdmin.setText("Cerrar sesión");
        jXTaskPaneContainer1.add(closeAdmin);

        jLayeredPane1.setBackground(new java.awt.Color(210, 210, 255));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(710, 750));
        jLayeredPane1.setLayout(new java.awt.CardLayout());

        Panel_RL.setBackground(new java.awt.Color(210, 210, 255));
        Panel_RL.setPreferredSize(new java.awt.Dimension(700, 720));
        Panel_RL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre del Laboratorio:");
        Panel_RL.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 118, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Registrar Laboratorios");
        Panel_RL.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 11, -1, -1));

        NameLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameLabActionPerformed(evt);
            }
        });
        Panel_RL.add(NameLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 115, 181, -1));

        jLabel3.setText("Nombre del Edificio:");
        Panel_RL.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 156, -1, -1));
        Panel_RL.add(Locacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(214, 153, 181, -1));

        BotonRegLab.setText("Crear");
        BotonRegLab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegLabActionPerformed(evt);
            }
        });
        Panel_RL.add(BotonRegLab, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 191, 87, -1));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ConsolaAdmin_back.jpg"))); // NOI18N
        jLabel38.setPreferredSize(new java.awt.Dimension(710, 750));
        Panel_RL.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 1080));

        jLayeredPane1.add(Panel_RL, "card2");

        Panel_RepL.setBackground(new java.awt.Color(210, 210, 255));
        Panel_RepL.setPreferredSize(new java.awt.Dimension(700, 720));
        Panel_RepL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Reportes de Centros de Cómputo");
        Panel_RepL.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 11, -1, -1));

        Eq_number.setBackground(new java.awt.Color(210, 210, 255));
        Eq_number.setText("Por número de equipos");
        Panel_RepL.add(Eq_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 207, -1, -1));

        Eq_status.setBackground(new java.awt.Color(210, 210, 255));
        Eq_status.setText("Por estado de los equipos");
        Panel_RepL.add(Eq_status, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 248, -1, -1));

        RepLabBox.setModel(new DefaultComboBoxModel(Control.ComboFill1("Nombre_C_C","Centro_Computo")));
        RepLabBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                RepLabBoxItemStateChanged(evt);
            }
        });
        Panel_RepL.add(RepLabBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(323, 327, 172, -1));

        RepLabButton.setLabel("Generar reporte");
        RepLabButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepLabButtonActionPerformed(evt);
            }
        });
        Panel_RepL.add(RepLabButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 400, -1, -1));

        jLabel6.setText("Elige un laboratorio");
        Panel_RepL.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 331, -1, -1));

        jLabel39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ConsolaAdmin_back.jpg"))); // NOI18N
        jLabel39.setPreferredSize(new java.awt.Dimension(710, 750));
        Panel_RepL.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 1080));

        jLayeredPane1.add(Panel_RepL, "card3");

        Eq_RegPane.setBackground(new java.awt.Color(210, 210, 255));
        Eq_RegPane.setPreferredSize(new java.awt.Dimension(700, 720));
        Eq_RegPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Registrar equipos");
        Eq_RegPane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 51, -1, -1));

        jLabel7.setText("Nombre del equipo");
        Eq_RegPane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 152, -1, -1));

        Eq_Name.setToolTipText("");
        Eq_RegPane.add(Eq_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 149, 124, -1));

        jLabel9.setText("Estado del  equipo");
        jLabel9.setToolTipText("");
        Eq_RegPane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 191, 89, -1));

        EqStatus_box.setModel(new DefaultComboBoxModel(Control.StatusComboFill()));
        Eq_RegPane.add(EqStatus_box, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 187, 124, -1));

        jLabel10.setText("Laboratorio del equipo");
        Eq_RegPane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 227, -1, -1));

        EqPlace_Box.setModel(new DefaultComboBoxModel(Control.ComboFill1("Nombre_C_C","Centro_Computo")));
        EqPlace_Box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EqPlace_BoxItemStateChanged(evt);
            }
        });
        Eq_RegPane.add(EqPlace_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 227, 124, -1));

        RegEqButton.setText("Crear equipo");
        RegEqButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegEqButtonActionPerformed(evt);
            }
        });
        Eq_RegPane.add(RegEqButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 291, -1, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ConsolaAdmin_back.jpg"))); // NOI18N
        jLabel40.setPreferredSize(new java.awt.Dimension(710, 750));
        Eq_RegPane.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 1080));

        jLayeredPane1.add(Eq_RegPane, "card4");

        Eq_DropPane.setBackground(new java.awt.Color(210, 210, 255));
        Eq_DropPane.setPreferredSize(new java.awt.Dimension(700, 720));
        Eq_DropPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Eliminar equipos");
        Eq_DropPane.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 52, -1, -1));

        jLabel12.setText("Nombre del equipo:");
        Eq_DropPane.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 185, -1, -1));

        EqName_Drop_Box.setModel(new DefaultComboBoxModel(Control.ComboFill2("Nombre_Eq","Ubicacion_Eq","A1","Equipo")));
        EqName_Drop_Box.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                EqName_Drop_BoxItemStateChanged(evt);
            }
        });
        Eq_DropPane.add(EqName_Drop_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 181, 143, -1));

        EqDrop_Button.setText("Eliminar");
        EqDrop_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EqDrop_ButtonActionPerformed(evt);
            }
        });
        Eq_DropPane.add(EqDrop_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 247, -1, -1));

        jLabel36.setText("Laboratorio:");
        Eq_DropPane.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 145, -1, -1));

        SelectLab_DropEq.setModel(new DefaultComboBoxModel(Control.ComboFill1("Nombre_C_C","Centro_Computo")));
        Eq_DropPane.add(SelectLab_DropEq, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 141, 143, -1));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ConsolaAdmin_back.jpg"))); // NOI18N
        jLabel41.setPreferredSize(new java.awt.Dimension(710, 750));
        Eq_DropPane.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 1080));

        jLayeredPane1.add(Eq_DropPane, "card6");

        Usr_UpdatePane.setBackground(new java.awt.Color(210, 210, 255));
        Usr_UpdatePane.setPreferredSize(new java.awt.Dimension(700, 720));
        Usr_UpdatePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("Actualizar datos de usuario");
        Usr_UpdatePane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 64, -1, -1));

        jLabel14.setText("Matrícula del usuario:");
        Usr_UpdatePane.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 213, -1, -1));

        jLabel15.setText("Nombre(s):");
        Usr_UpdatePane.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 251, -1, -1));

        jLabel16.setText("Apellido paterno:");
        Usr_UpdatePane.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 289, -1, -1));

        jLabel17.setText("Apellido materno:");
        Usr_UpdatePane.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 327, -1, -1));

        jLabel18.setText("Contraseña:");
        Usr_UpdatePane.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 365, -1, -1));

        jLabel19.setText("Confirmar contraseña:");
        Usr_UpdatePane.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 403, -1, -1));

        Upd_Matricula.setToolTipText("");
        Usr_UpdatePane.add(Upd_Matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 210, 122, -1));
        Usr_UpdatePane.add(Upd_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 248, 122, -1));
        Usr_UpdatePane.add(UPD_AP_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 286, 122, -1));
        Usr_UpdatePane.add(Upd_AP_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 324, 122, -1));
        Usr_UpdatePane.add(Upd_Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 362, 122, -1));

        Upd_Button.setText("Actualizar");
        Upd_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Upd_ButtonActionPerformed(evt);
            }
        });
        Usr_UpdatePane.add(Upd_Button, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 469, -1, -1));
        Usr_UpdatePane.add(Upd_RevPswd, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 400, 122, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ConsolaAdmin_back.jpg"))); // NOI18N
        jLabel42.setPreferredSize(new java.awt.Dimension(710, 750));
        Usr_UpdatePane.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 1080));

        jLayeredPane1.add(Usr_UpdatePane, "card5");

        ReportsPane.setBackground(new java.awt.Color(210, 210, 255));
        ReportsPane.setPreferredSize(new java.awt.Dimension(700, 720));
        ReportsPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("Generar reportes");
        ReportsPane.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 43, -1, -1));

        jLabel21.setText("Tipo");
        ReportsPane.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 101, -1, -1));

        RBType1.setBackground(new java.awt.Color(210, 210, 255));
        RBType1.setText("Eventos");
        ReportsPane.add(RBType1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 131, -1, -1));

        RBType2.setBackground(new java.awt.Color(210, 210, 255));
        RBType2.setText("Errores");
        ReportsPane.add(RBType2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 155, -1, -1));

        RBType3.setBackground(new java.awt.Color(210, 210, 255));
        RBType3.setText("Programas ejecutados");
        ReportsPane.add(RBType3, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 178, -1, -1));

        jLabel22.setText("Laboratorio");
        ReportsPane.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 101, -1, -1));

        Repo_Lab.setModel(new DefaultComboBoxModel(Control.ComboFill1("Nombre_C_C","Centro_Computo")));
        ReportsPane.add(Repo_Lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 131, 110, -1));

        jLabel23.setText("Equipo");
        ReportsPane.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 101, -1, -1));

        Repo_Eq.setModel(new DefaultComboBoxModel(Control.ComboFill2("Nombre_Eq","Ubicacion_Eq","A1","Equipo")));
        ReportsPane.add(Repo_Eq, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 131, 109, -1));

        jLabel8.setText("Fecha / hora de inicio:");
        ReportsPane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 239, -1, -1));

        jLabel24.setText("Día");
        ReportsPane.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 275, -1, -1));

        DiaIni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        ReportsPane.add(DiaIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 271, 50, -1));

        jLabel25.setText("Mes");
        ReportsPane.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 303, -1, -1));

        MesIni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        ReportsPane.add(MesIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 299, 50, -1));

        jLabel26.setText("Año");
        ReportsPane.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 331, -1, -1));

        AnoIni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));
        ReportsPane.add(AnoIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 327, -1, -1));

        jLabel27.setText("Hora");
        ReportsPane.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 371, -1, -1));

        HoraIni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        ReportsPane.add(HoraIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 367, 50, -1));

        jLabel28.setText("Min");
        ReportsPane.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 399, -1, -1));

        MinIni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        ReportsPane.add(MinIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 395, 50, -1));

        jLabel29.setText("Fecha / hora de fin:");
        ReportsPane.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 239, -1, -1));

        jLabel30.setText("Día");
        ReportsPane.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 275, -1, -1));

        jLabel31.setText("Mes");
        ReportsPane.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 303, -1, -1));

        jLabel32.setText("Año");
        ReportsPane.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(278, 331, -1, -1));

        jLabel33.setText("Hora");
        ReportsPane.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 371, -1, -1));

        jLabel34.setText("Min");
        ReportsPane.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 399, -1, -1));

        DiaFin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        ReportsPane.add(DiaFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 271, 50, -1));

        MesFin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        ReportsPane.add(MesFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 299, 50, -1));

        AnoFin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));
        ReportsPane.add(AnoFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 327, -1, -1));

        HoraFin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));
        ReportsPane.add(HoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 367, 50, -1));

        MinFin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        ReportsPane.add(MinFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 395, 50, -1));

        RepoButton.setText("Crear reporte");
        RepoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepoButtonActionPerformed(evt);
            }
        });
        ReportsPane.add(RepoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 484, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ConsolaAdmin_back.jpg"))); // NOI18N
        jLabel43.setPreferredSize(new java.awt.Dimension(710, 750));
        ReportsPane.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 1080));

        jLayeredPane1.add(ReportsPane, "card7");

        TempCleanPane.setBackground(new java.awt.Color(210, 210, 255));
        TempCleanPane.setPreferredSize(new java.awt.Dimension(700, 720));
        TempCleanPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cleanButton.setText("Realizar Limpieza");
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });
        TempCleanPane.add(cleanButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 235, -1, -1));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel35.setText("Limpieza de archivos temporales");
        TempCleanPane.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 20, -1, -1));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/ConsolaAdmin_back.jpg"))); // NOI18N
        jLabel44.setPreferredSize(new java.awt.Dimension(710, 750));
        TempCleanPane.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 1080));

        jLayeredPane1.add(TempCleanPane, "card8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(704, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 190, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXTaskPaneContainer1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    ButtonGroup bgRepLab = new ButtonGroup();
    private void NameLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameLabActionPerformed

    private void BotonRegLabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegLabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonRegLabActionPerformed

    private void EqDrop_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EqDrop_ButtonActionPerformed
            /*/ TODO add your handling code here:
        if(Equipo.bajaEq(EqName_Drop_Box.getSelectedItem().toString())){
            EqName_Drop_Box.setModel(new DefaultComboBoxModel(CC.llenar1("Nombre_Eq","Ubicacion_Eq",SelectLab_DropEq.getSelectedItem().toString(),"Equipo")));
        }
    }//GEN-LAST:event_EqDrop_ButtonActionPerformed
*/
        if(Control.EliminarEquipo(EqName_Drop_Box.getSelectedItem().toString())){
            EqName_Drop_Box.setModel(new DefaultComboBoxModel(Control.ComboFill2("Nombre_Eq","Ubicacion_Eq",SelectLab_DropEq.getSelectedItem().toString(),"Equipo")));
        }
}
    private void Upd_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Upd_ButtonActionPerformed
        /*/ TODO add your handling code here:
        Usr.check(Upd_Matricula.getText(),Upd_Name.getText() , UPD_AP_P.getText(), Upd_AP_M.getText(), Upd_Pass.getText(), Upd_RevPswd.getText());
    }//GEN-LAST:event_Upd_ButtonActionPerformed
*/
         Control.UsrCheck(Upd_Matricula.getText(),Upd_Name.getText() , UPD_AP_P.getText(), Upd_AP_M.getText(), Upd_Pass.getText(), Upd_RevPswd.getText());
}
    private void RepLabButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepLabButtonActionPerformed
        // TODO add your handling code here:
        if(Eq_number.isSelected()){
            try{
                path = getClass().getResource("/Reports/LabReport.jasper").getPath();
                path = URLDecoder.decode(path,"UTF-8"); 
                Connection cn = new ConexionDB().conectar();
                Map parametros = new HashMap();
                parametros.put("@ubicacion",RepLabBox.getSelectedItem().toString());
                JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
                JasperPrint imprimir = JasperFillManager.fillReport(reporte,parametros,cn);
                JasperViewer visor = new JasperViewer(imprimir,false);
                visor.setTitle("Reporte de numero de equipos");
                visor.setVisible(true);
                
            }catch(Exception e){
                  JOptionPane.showMessageDialog(this, "Error: "+e.toString());
              
            }
            
        }else if(Eq_status.isSelected()){
            try{
                path = getClass().getResource("/Reports/RepStatusLab.jasper").getPath();
                path = URLDecoder.decode(path,"UTF-8"); 
                Connection cn = new ConexionDB().conectar();
                Map parametros = new HashMap();
                parametros.put("@laboratorio",RepLabBox.getSelectedItem().toString());
                JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
                JasperPrint imprimir = JasperFillManager.fillReport(reporte,parametros,cn);
                JasperViewer visor = new JasperViewer(imprimir,false);
                visor.setTitle("Reporte de estado de equipos");
                visor.setVisible(true);
                
            }catch(Exception e){
                  JOptionPane.showMessageDialog(this, "Error: "+e.toString());
              
            }
        }else{
            JOptionPane.showMessageDialog(this,"Por favor, elige un tipo de reporte");
        }
    }//GEN-LAST:event_RepLabButtonActionPerformed

    private void RepoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepoButtonActionPerformed
        // TODO add your handling code here:
        String HoraI="";
        String HoraF="";
        String Equipo="";
        HoraI=AnoIni.getSelectedItem().toString()+"-"+MesIni.getSelectedItem().toString()+"-"+DiaIni.getSelectedItem().toString()+"T"+HoraIni.getSelectedItem().toString()+":"+MinIni.getSelectedItem().toString()+":00";
        HoraF=AnoFin.getSelectedItem().toString()+"-"+MesFin.getSelectedItem().toString()+"-"+DiaFin.getSelectedItem().toString()+"T"+HoraFin.getSelectedItem().toString()+":"+MinFin.getSelectedItem().toString()+":00";
        Equipo = Repo_Eq.getSelectedItem().toString();
        if(RBType1.isSelected()){
            //-----------------reporte de eventos
            try{
                path = getClass().getResource("/Reports/Report_Evt.jasper").getPath();
                path = URLDecoder.decode(path,"UTF-8"); 
                Connection cn = new ConexionDB().conectar();
                Map parametros = new HashMap();
                parametros.put("@name_Equipo",Equipo);
                parametros.put("@horaInicio",HoraI);
                parametros.put("@horaFin",HoraF);
                JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
                JasperPrint imprimir = JasperFillManager.fillReport(reporte,parametros,cn);
                JasperViewer visor = new JasperViewer(imprimir,false);
                visor.setTitle("Reporte de errores");
                visor.setVisible(true);
                
            }catch(Exception e){
                  JOptionPane.showMessageDialog(this, "Error: "+e.toString());
            }
        }else if(RBType2.isSelected()){
            //--------------------reporte de errores
            try{
                path = getClass().getResource("/Reports/Report_Error.jasper").getPath();
                path = URLDecoder.decode(path,"UTF-8"); 
                Connection cn = new ConexionDB().conectar();
                Map parametros = new HashMap();
                parametros.put("@name_Equipo",Equipo);
                parametros.put("@horaInicio",HoraI);
                parametros.put("@horaFin",HoraF);
                JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
                JasperPrint imprimir = JasperFillManager.fillReport(reporte,parametros,cn);
                JasperViewer visor = new JasperViewer(imprimir,false);
                visor.setTitle("Reporte de errores");
                visor.setVisible(true);
                
            }catch(Exception e){
                  JOptionPane.showMessageDialog(this, "Error: "+e.toString());
            }
            
        }else if(RBType3.isSelected()){
            //---------------------reporte de programas
            try{
                path = getClass().getResource("/Reports/Report_Prgm.jasper").getPath();
                path = URLDecoder.decode(path,"UTF-8"); 
                Connection cn = new ConexionDB().conectar();
                Map parametros = new HashMap();
                parametros.put("@name_Equipo",Equipo);
                parametros.put("@horaInicio",HoraI);
                parametros.put("@horaFin",HoraF);
                JasperReport reporte = (JasperReport)JRLoader.loadObject(path);
                JasperPrint imprimir = JasperFillManager.fillReport(reporte,parametros,cn);
                JasperViewer visor = new JasperViewer(imprimir,false);
                visor.setTitle("Reporte de errores");
                visor.setVisible(true);
                
            }catch(Exception e){
                  JOptionPane.showMessageDialog(this, "Error: "+e.toString());
            }
        }else{
            JOptionPane.showMessageDialog(this,"Por favor, elige un tipo de reporte");
        }
    }//GEN-LAST:event_RepoButtonActionPerformed

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
            // TODO add your handling code here:
        Control.MantainanceCleanTemp();
    }//GEN-LAST:event_cleanButtonActionPerformed

    private void RegEqButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegEqButtonActionPerformed
        /*// TODO add your handling code here:/*
        Control.RegistrarEquipo(Eq_Name.getText(), EqPlace_Box.getSelectedItem().toString(),EqStatus_box.getSelectedItem().toString());
    }//GEN-LAST:event_RegEqButtonActionPerformed

        }
     //*/Control.RegistrarEquipo(Eq_Name.getText(), EqPlace_Box.getSelectedItem().toString(),EqStatus_box.getSelectedItem().toString());
        
    }
     
    private void RepLabBoxItemStateChanged(java.awt.event.ItemEvent evt) {                                           
        // TODO add your handling code here:
        if(Eq_status.isSelected()==true){
                    RepLabButton.setEnabled(true);
                }else if(Eq_number.isSelected()==true){
                    RepLabButton.setEnabled(true);
                }
    }
    
    private void EqPlace_BoxItemStateChanged(java.awt.event.ItemEvent evt) {                                             
        // TODO add your handling code here:
        if(Eq_Name.getText()!=null&&EqStatus_box.getSelectedItem().toString()!=null&&EqPlace_Box.getSelectedItem().toString()!=null){
            RegEqButton.setEnabled(true);
        }
    }   
    
    private void EqName_Drop_BoxItemStateChanged(java.awt.event.ItemEvent evt) {                                                 
        // TODO add your handling code here:
        if(SelectLab_DropEq.getSelectedItem().toString()!=null&&EqName_Drop_Box.getSelectedItem().toString()!=null){
            EqDrop_Button.setEnabled(true);
        }
    }  
    
    public void ToggleAL(){
        if(Panel_RL!=null){
            Panel_RepL.setVisible(false);
            Eq_RegPane.setVisible(false);
            Eq_DropPane.setVisible(false);
            Usr_UpdatePane.setVisible(false);
             ReportsPane.setVisible(false);
             TempCleanPane.setVisible(false);
            
            Panel_RL.setVisible(true);
        }
        //return null;
    }
    public void ToggleRL(){
        Panel_RL.setVisible(false);
        Eq_RegPane.setVisible(false);
        Eq_DropPane.setVisible(false);
        Usr_UpdatePane.setVisible(false);
         ReportsPane.setVisible(false);
         TempCleanPane.setVisible(false);
        
        Panel_RepL.setVisible(true);
        
        //return null;
    }
    
    public void ToggleERP(){
        Panel_RL.setVisible(false);
        Panel_RepL.setVisible(false);
        Eq_DropPane.setVisible(false);
        Usr_UpdatePane.setVisible(false);
         ReportsPane.setVisible(false);
         TempCleanPane.setVisible(false);
        
        Eq_RegPane.setVisible(true);
        
    }
    
    public void ToggleEDP(){
        Panel_RL.setVisible(false);
        Panel_RepL.setVisible(false);
        Eq_RegPane.setVisible(false);
        Usr_UpdatePane.setVisible(false);
         ReportsPane.setVisible(false);
         TempCleanPane.setVisible(false);
        
        Eq_DropPane.setVisible(true);
    }
    
    public void ToggleUUP(){
        Panel_RL.setVisible(false);
        Panel_RepL.setVisible(false);
        Eq_RegPane.setVisible(false);
        Eq_DropPane.setVisible(false);
        ReportsPane.setVisible(false);
        TempCleanPane.setVisible(false);
        
        Usr_UpdatePane.setVisible(true);
    }
    
    public void ToggleRP(){
        Panel_RL.setVisible(false);
        Panel_RepL.setVisible(false);
        Eq_RegPane.setVisible(false);
        Eq_DropPane.setVisible(false);
        Usr_UpdatePane.setVisible(false);
        TempCleanPane.setVisible(false);
        
        ReportsPane.setVisible(true);
    }
    
    public void ToggleTCP(){
        
        Panel_RL.setVisible(false);
        Panel_RepL.setVisible(false);
        Eq_RegPane.setVisible(false);
        Eq_DropPane.setVisible(false);
        Usr_UpdatePane.setVisible(false);
        ReportsPane.setVisible(false);
        
        TempCleanPane.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox AnoFin;
    private javax.swing.JComboBox AnoIni;
    private javax.swing.JButton BotonRegLab;
    private javax.swing.JComboBox DiaFin;
    private javax.swing.JComboBox DiaIni;
    private javax.swing.JButton EqDrop_Button;
    private javax.swing.JComboBox EqName_Drop_Box;
    private javax.swing.JComboBox EqPlace_Box;
    private javax.swing.JComboBox EqStatus_box;
    private javax.swing.JPanel Eq_DropPane;
    private javax.swing.JTextField Eq_Name;
    private javax.swing.JPanel Eq_RegPane;
    private javax.swing.JRadioButton Eq_number;
    private javax.swing.JRadioButton Eq_status;
    private javax.swing.ButtonGroup GrupoBotRepLab;
    private javax.swing.ButtonGroup GrupoReportes;
    private javax.swing.JComboBox HoraFin;
    private javax.swing.JComboBox HoraIni;
    private javax.swing.JTextField Locacion;
    private javax.swing.JComboBox MesFin;
    private javax.swing.JComboBox MesIni;
    private javax.swing.JComboBox MinFin;
    private javax.swing.JComboBox MinIni;
    private javax.swing.JTextField NameLab;
    private javax.swing.JPanel Panel_RL;
    private javax.swing.JPanel Panel_RepL;
    private javax.swing.JRadioButton RBType1;
    private javax.swing.JRadioButton RBType2;
    private javax.swing.JRadioButton RBType3;
    private javax.swing.JButton RegEqButton;
    private javax.swing.JComboBox RepLabBox;
    private javax.swing.JButton RepLabButton;
    private javax.swing.JButton RepoButton;
    private javax.swing.JComboBox Repo_Eq;
    private javax.swing.JComboBox Repo_Lab;
    private javax.swing.JPanel ReportsPane;
    private javax.swing.JComboBox SelectLab_DropEq;
    private org.jdesktop.swingx.JXTaskPane TaskPaneLabs;
    private org.jdesktop.swingx.JXTaskPane TaskPaneMantainance;
    private org.jdesktop.swingx.JXTaskPane TaskPaneReports;
    private org.jdesktop.swingx.JXTaskPane TaskPaneStock;
    private org.jdesktop.swingx.JXTaskPane TaskPaneUsrs;
    private javax.swing.JPanel TempCleanPane;
    private javax.swing.JTextField UPD_AP_P;
    private javax.swing.JTextField Upd_AP_M;
    private javax.swing.JButton Upd_Button;
    private javax.swing.JTextField Upd_Matricula;
    private javax.swing.JTextField Upd_Name;
    private javax.swing.JPasswordField Upd_Pass;
    private javax.swing.JPasswordField Upd_RevPswd;
    private javax.swing.JPanel Usr_UpdatePane;
    private javax.swing.JButton cleanButton;
    private javax.swing.JButton closeAdmin;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
