/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package View;

import Controller.Control;
import Controller.Monitor;
import Controller.jBlocked;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Adán
 */
public class GUI_Usr extends javax.swing.JFrame {

    Control Control = new Control();
    private GraphicsDevice gd;
    jBlocked block = new jBlocked(this);
    ConsolaAdmin Console = new ConsolaAdmin();
    Usr_Form sesion = new Usr_Form();
    Monitor thread;
    
    /**
     * Creates new form GUI_Usr
     */
    public GUI_Usr() {
        this.setUndecorated(true);
        this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
        this.setVisible(true);
        this.setDefaultCloseOperation( DO_NOTHING_ON_CLOSE  );//evita cerra jframe con ALT+C
        this.setExtendedState( MAXIMIZED_BOTH );//maximizado
        this.setAlwaysOnTop(true);//siempre al frente 
        //nueva instancia de jBlocked pasando como parametros e este JFrame
        block.block();
        initComponents();
    }

    
    

    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogUsrPane = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        lablePass = new javax.swing.JLabel();
        tfMatricula = new javax.swing.JTextField();
        pfPass = new javax.swing.JPasswordField();
        pfPass.addKeyListener(new KeyAdapter(){
            public void keyPressed(KeyEvent e){
                if(tfMatricula.getText()!=null&&pfPass.getText()!=null){
                    loginButton.setEnabled(true);
                }
            }
        });
        loginButton = new javax.swing.JButton();
        loginButton.setEnabled(false);
        signinButton = new javax.swing.JButton();
        signinButton.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae){
                //block.pause();
                LogUsrPane.setVisible(false);                    
                RegUsrPane.setVisible(true);

                keyword.setEnabled(false);
                name.setEnabled(false);
                LastName_P.setEnabled(false);
                lastName_M.setEnabled(false);
                pass.setEnabled(false);
                checkPass.setEnabled(false);

                keyword.setEnabled(true);
                name.setEnabled(true);
                LastName_P.setEnabled(true);
                lastName_M.setEnabled(true);
                pass.setEnabled(true);
                checkPass.setEnabled(true);
            }
        });
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RegUsrPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        keyword = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        LastName_P = new javax.swing.JTextField();
        lastName_M = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        checkPass = new javax.swing.JPasswordField();
        checkPass.addKeyListener(new KeyAdapter(){
            public void keyPressed(KeyEvent e){
                if(keyword.getText()!=null&&name.getText()!=null&&LastName_P.getText()!=null&&lastName_M.getText()!=null&&pass.getText()!=null&&checkPass.getText()!=null){
                    signButton.setEnabled(true);
                }
            }
        });
        signButton = new javax.swing.JButton();
        signButton.setEnabled(false);
        backButton = new javax.swing.JButton();
        backButton.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent ae){
                RegUsrPane.setVisible(false);
                LogUsrPane.setVisible(true);

                tfMatricula.setEnabled(false);
                pfPass.setEnabled(false);

                tfMatricula.setEnabled(true);
                pfPass.setEnabled(true);
            }
        });
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(204, 204, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new java.awt.CardLayout());

        LogUsrPane.setBackground(new java.awt.Color(210, 210, 255));
        LogUsrPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelName.setText("Número de cuenta");
        LogUsrPane.add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 93, -1, -1));

        lablePass.setText("Contraseña");
        LogUsrPane.add(lablePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 131, -1, -1));
        LogUsrPane.add(tfMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 90, 99, -1));

        pfPass.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        LogUsrPane.add(pfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 128, 99, -1));

        loginButton.setText("Iniciar sesión");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        LogUsrPane.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 182, -1, -1));

        signinButton.setText("Registrarse");
        LogUsrPane.add(signinButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 300, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel8.setText("Bienvenido a CAL");
        LogUsrPane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 16, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/log_in_back.jpg"))); // NOI18N
        jLabel9.setAlignmentY(0.0F);
        jLabel9.setMaximumSize(new java.awt.Dimension(1160, 860));
        jLabel9.setMinimumSize(new java.awt.Dimension(1160, 1860));
        jLabel9.setPreferredSize(new java.awt.Dimension(1160, 860));
        LogUsrPane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(LogUsrPane, "card2");

        RegUsrPane.setBackground(new java.awt.Color(210, 210, 255));
        RegUsrPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Registro de usuarios");
        RegUsrPane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1596, 38, -1, -1));

        jLabel2.setText("Matricula:");
        RegUsrPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 124, -1, -1));

        jLabel3.setText("Nombre:");
        RegUsrPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 150, -1, -1));

        jLabel4.setText("Apellido paterno:");
        RegUsrPane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 176, -1, -1));

        jLabel5.setText("Apellido materno:");
        RegUsrPane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 202, -1, -1));

        jLabel6.setText("Contraseña:");
        RegUsrPane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 228, -1, -1));

        jLabel7.setText("Repite contraseña:");
        RegUsrPane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 254, -1, -1));
        RegUsrPane.add(keyword, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 121, 99, -1));
        RegUsrPane.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 147, 99, -1));
        RegUsrPane.add(LastName_P, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 173, 99, -1));
        RegUsrPane.add(lastName_M, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 199, 99, -1));
        RegUsrPane.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 225, 99, -1));
        RegUsrPane.add(checkPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 251, 99, -1));

        signButton.setText("Registrarse");
        signButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signButtonActionPerformed(evt);
            }
        });
        RegUsrPane.add(signButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 305, -1, -1));

        backButton.setText("Volver");
        RegUsrPane.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 305, 99, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign_in_back.jpg"))); // NOI18N
        jLabel10.setMaximumSize(new java.awt.Dimension(1160, 860));
        jLabel10.setMinimumSize(new java.awt.Dimension(1160, 860));
        jLabel10.setPreferredSize(new java.awt.Dimension(1160, 860));
        RegUsrPane.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(RegUsrPane, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        String check="";
        /*
        check=Log.iniciarSesion(tfMatricula.getText(),pfPass.getText());
                */
        check=Control.FirstDecrypt(Control.IniciarSesion(tfMatricula.getText(),pfPass.getText()));
        switch(check){
            case "1":
                JOptionPane.showMessageDialog(this,"Bienvenido");
                Console.setVisible(true);
                this.dispose();
            break;
            case "2":
                JOptionPane.showMessageDialog(this,"Bienvenido");
                /*thread = new Monitor(tfMatricula.getText());
                thread.launcher();*/
                sesion.launch();
                this.dispose();
            break;
            default:
                JOptionPane.showMessageDialog(this,"Error, datos inválidos, vuelva a intentarlo");
            break;
        }
        
    }//GEN-LAST:event_loginButtonActionPerformed

    private void signButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signButtonActionPerformed
        // TODO add your handling code here:
        String check="";
        check=Control.SignInCheck(keyword.getText(), name.getText(), LastName_P.getText(), lastName_M.getText(), pass.getText(), checkPass.getText());
        if(check.equals("Operación exitosa")){
            JOptionPane.showMessageDialog(this,check);
            RegUsrPane.setVisible(false);
            LogUsrPane.setVisible(true);

            tfMatricula.setEnabled(false);
            pfPass.setEnabled(false);

            tfMatricula.setEnabled(true);
            pfPass.setEnabled(true);
        }else {
            JOptionPane.showMessageDialog(this,check);
        }
    }//GEN-LAST:event_signButtonActionPerformed
    
        
    
    public void showMessage(String msj){
        JOptionPane.showMessageDialog(this,msj);
    }
    
    public void lanza(){
       this.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField LastName_P;
    private javax.swing.JPanel LogUsrPane;
    private javax.swing.JPanel RegUsrPane;
    private javax.swing.JButton backButton;
    private javax.swing.JPasswordField checkPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField keyword;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel lablePass;
    private javax.swing.JTextField lastName_M;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pfPass;
    private javax.swing.JButton signButton;
    private javax.swing.JButton signinButton;
    private javax.swing.JTextField tfMatricula;
    // End of variables declaration//GEN-END:variables
}
